### ISSUE TITLE
Can you provide a pretrained model for LibriTTS?

### ISSUE THREAD

**Issue by zjlww** [richardbaihe/a3t#2]
Hi, we would like to compare our work with your results on LibriTTS dataset. Can you share a pretrained model trained on LibriTTS? It would be very helpful! Many thanks in advance.

**Comment by richardbaihe** [comment]
Hi @zjlww, I am contacting my colleagues to see if they have a copy. Will let you know when I got them.

**Comment by richardbaihe** [comment]
Hi @zjlww, sorry for this late response. Now I get the finetuned TTS model in Table.8 but not the pretrained A3T. Is this the model you are looking for? If so, please download it from [here](https://huggingface.co/richardbaihe/a3t-libritts)
