### ISSUE TITLE
Where to find vctk_spk2xvector.pt

### ISSUE THREAD

**Issue by lematt1991** [richardbaihe/a3t#3]
Hi!  I'm trying to run the `sedit_mcd.py` script, but the [`vctk_spk2xvector.pt`](https://github.com/richardbaihe/a3t/blob/dev_richard/aggregate_output/sedit_mcd.py#L38) file seems to be missing.  Is it possible to include this file or point me to where it might be publicly available?  Thanks!

**Comment by richardbaihe** [comment]
uploaded. see [this](https://github.com/richardbaihe/a3t/commit/9230e75e79804b888ffc3af1bc19050eaff9db95)
