### ISSUE TITLE
Trying to reproduce MCD results for VCTK

### ISSUE THREAD

**Issue by lematt1991** [richardbaihe/a3t#4]
Hi, I'm trying to reproduce the MCD results.  I've been able to run the `sedit_mcd.py` script (without the vctk_spk2xvector.pt - see #3), but am getting numbers higher than what's reported in the paper.  I needed to make some changes in order to get it to run which you can see [here](https://github.com/richardbaihe/a3t/compare/dev_richard...lematt1991:a3t:run-mcd?expand=1), but these are mostly patching paths.  I downloaded the A3T model checkpoint from [huggingface](https://huggingface.co/richardbaihe/a3t-vctk/tree/main/conformer) and downloaded the fs2 model from the espnet model zoo with the following code:

```Python
from espnet_model_zoo.downloader import ModelDownloader

key = "kan-bayashi/vctk_tts_train_gst+xvector_conformer_fastspeech2_transformer_teacher_raw_phn_tacotron_g2p_en_no_space_train.loss.ave"
d = ModelDownloader("~/.cache/espnet")  # Specify cachedir
d.download_and_unpack(key)
```

With this, I'm able to successfully run the `sedit_mcd.py` script comparing the replaced GT wav files to the replaced sedit wavfiles, but get a mean MCD of 10.59:

```
span_diff:-19.966666666666665
sedit_replaced:
python /private/home/mattle/a3t/aggregate_output/../utils/mcd_calculate.py --mcep_dim 80 --wavdir /private/home/mattle/a3t/aggregate_output/mcd/vctk/sedit/replaced --gtwavdir /private/home/mattle/a3t/aggregate_output/mcd/vctk/gt/replaced --f0min 80 --f0max 7600 --shiftms 300 --silenced 1
number of utterances = 30
Mean MCD: 10.59
```

I believe this number should be 8.09 (Table 2).  Any ideas what I might be doing wrong or why the numbers don't match those reported in the paper?  Thanks in advance for any help!

**Comment by richardbaihe** [comment]
Hi @lematt1991, thank you for interesting in our work!

First, Table 2 is an ablation study with LJSpeech Dataset, where the model are trained and evaluated with LJSpeech dataset.

Second, I will upload the vctk_spk2xvector.pt  soon.

Finally, to evaluate the VCTK MCD, for example, Table3, I can first send you our generations. Then, I will try to generate these generations again and let you know once I tested. You can send me a email and I will reply with these generation files.

**Comment by richardbaihe** [comment]
Hi @lematt1991, I just updated the MCD script which can reproduce our Table3 results. See this [commit](https://github.com/richardbaihe/a3t/commit/97ede28ae65778ba296928b4b81a50c9bbaa7956).

Please use `unseen_conformer` checkpoint for Table 3, which was trained by excluding some speakers's data. I noticed you was using the `conformer` checkpoint in your descriptions.

**Comment by lematt1991** [comment]
Thanks @richardbaihe!  With this, I'm able to reproduce the 80% mask rate, unseen MCD result of Table 3 (actually even slightly better results):

```
number of utterances = 30
Mean MCD: 9.55
```

Thanks for your help!
