### ISSUE TITLE
Is the pretrained models for sedit task be publicly available?

### ISSUE THREAD

**Issue by TinaChen95** [richardbaihe/a3t#6]
The demos for tasks are great!
Just wondering where can I find these two models 
 https://github.com/richardbaihe/a3t/blob/97ede28ae65778ba296928b4b81a50c9bbaa7956/espnet2/bin/sedit_inference.py#L868 and https://github.com/richardbaihe/a3t/blob/97ede28ae65778ba296928b4b81a50c9bbaa7956/espnet2/bin/sedit_inference.py#L884 

Thanks!

**Comment by richardbaihe** [comment]
The fs2 model can be found here: https://github.com/espnet/espnet_model_zoo/blob/master/espnet_model_zoo/table.csv

The vocoder is from here: https://github.com/kan-bayashi/ParallelWaveGAN

**Comment by richardbaihe** [comment]
Hi @TinaChen95, I am closing this issue if no more questions. Thanks for your interest again~
