### ISSUE TITLE
Error loading libritts model

### ISSUE THREAD

**Issue by lematt1991** [richardbaihe/a3t#7]
**Describe the bug**
I'm trying to load the [LibrittsPretrainedLibrittsFinetuned](https://huggingface.co/richardbaihe/a3t-libritts/tree/main/LibrittsPretrainedLibrittsFinetuned), but am running into a few errors.  Here is what I have so far:

```Python
import yaml
from espnet2.tasks.mlm import MLMTask
import torch
from argparse import Namespace
from huggingface_hub import hf_hub_download


repo_id = "richardbaihe/a3t-libritts"
chkpnt_file = hf_hub_download(repo_id=repo_id, filename="LibrittsPretrainedLibrittsFinetuned/train.loss.ave_5best.pth")
chkpnt = torch.load(chkpnt_file)
config = yaml.safe_load(open(hf_hub_download(repo_id=repo_id, filename="LibrittsPretrainedLibrittsFinetuned/config.yaml")))
args = Namespace(**config)
args.use_scaled_pos_enc=False  # <- This is missing from the config, set to False to match vctk config?
model = MLMTask.build_model(args)
model.load_state_dict(chkpnt)
```

I needed to download a `feats_stats.npz` file, which I found [here](https://huggingface.co/imdanboy/ljspeech_tts_train_jets_raw_phn_tacotron_g2p_en_no_space_train.total_count.ave/blob/main/exp/tts_stats_raw_phn_tacotron_g2p_en_no_space/train/feats_stats.npz).  I think this should be the right one?

With this I'm still getting the following error:

```
AttributeError: 'Namespace' object has no attribute 'encoder'
```

Is there an updated config that I can use to load the model, or am I doing something wrong?  Thanks for your help in advance!

**Comment by richardbaihe** [comment]
Hi @lematt1991 , this is a TTS model finetuned with A3T checkpoints. so, the task is not`MLMTask `, but `from espnet2.tasks.tts import TTSTask`. Hope this help solve your problem.

**Comment by lematt1991** [comment]
Ah that was it, now it's loading.  Thank you!

**Comment by lematt1991** [comment]
@richardbaihe is the libritts pre-trained A3T model publicly available?  Or only the one finetuned on the TTS task?  Thanks!

**Comment by richardbaihe** [comment]
@lematt1991 for Libritts, only finetuned checkpoints have been open-sourced. Sorry for any inconvenience...

**Comment by lematt1991** [comment]
OK, thanks for clarifying
