### ISSUE TITLE
 parse_options.sh not found

### ISSUE THREAD

**Issue by 0xhlc** [richardbaihe/a3t#9]
Thank you very much for your work!
I want to  run the python script `bin/sedit_inference.py`. In the Prepare data stage, I  execute the command `./run.sh --stage 0 --stop_stage 5` according to [readme.md](https://github.com/richardbaihe/a3t/blob/dev_richard/egs2/vctk/sedit/README.md), an error occurs on line 129 of [mlm.sh](https://github.com/richardbaihe/a3t/blob/dev_richard/egs2/vctk/sedit/mlm.sh).
`parse_options.sh` not found.

**Comment by richardbaihe** [comment]
sorry for the late response. 
in this case, you don't have kaldi installed and please refer to this link: https://espnet.github.io/espnet/installation.html#step-2-installation-espnet

a quick fix would be running:
`bash ci/install_kaldi.sh`


I think I should update the docker image to make sure kaldi is installed inside....
